version: '3.5'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - ${RABBIT_PORT}:5672
      - ${WEB_RABBIT_MQ}:15672
    env_file:
      - .env
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    networks:
      - llm_wrap_network

  redis:
    image: "redis:alpine"
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/var/lib/data
    networks:
      - llm_wrap_network

  celery_worker:
    build: .
    depends_on:
      - rabbitmq
      - redis
    networks:
      - llm_wrap_network
    env_file:
      - .env
    command: celery -A protollm_sdk.celery.app worker --loglevel=info

  flower:
    build: .
    ports:
      - ${FLOWER_PORT}:7672
    depends_on:
      - rabbitmq
      - celery_worker
    networks:
      - llm_wrap_network
    env_file:
      - .env
    command: sh -c "sleep 20 && celery -A protollm_sdk.celery.app flower --broker=${CELERY_BROKER_URL} --port=7672"

  server:
    image: chromadb/chroma:latest
    env_file:
      - .env
    environment:
      - IS_PERSISTENT=TRUE
    ports:
      - ${VECTOR_PORT}:8000
    networks:
      - llm_wrap_network

  embedding_server:
    image: ${EMBEDDING_IMAGE}
    command: --model-id ${ST_MODEL} --revision ${ST_MODEL_REVISION}
    ports:
      - ${EMBEDER_PORT}:80
    networks:
      - llm_wrap_network

volumes:
  rabbitmq_data:
  redis_data:

networks:
  llm_wrap_network:
    name: llm_wrap_network
    driver: bridge
